#:schema node_modules/wrangler/config-schema.json
name = "sagafarmann"
compatibility_date = "2024-11-12"
pages_build_output_dir = "./build/client"

[vars]
API_URL="https://sagafarmann-api.patient-lab-9126.workers.dev"
TURNSTILE_SITE_KEY="0x4AAAAAAA2OYQhcu3voq9Rz"